version: 2
updates:
  # ==============
  # KOTLIN BACKEND
  # ==============

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      jvm:
        patterns:
          - "jvm"
      alt:
        patterns:
          - "ca*"
          - "com*"
          - "io*"
          - "no*"
          - "org*"


  # ==============
  # GITHUB ACTIONS
  # ==============

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"