name: Release common-test

on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    paths:
      - common-test

jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build
      - name: Test and build
        run: ./gradlew :common-test:test :common-test:build

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(echo $GITHUB_SHA | cut -c 1-12)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: common-test.${{ env.RELEASE_TAG }}
          release_name: common-test.${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
      - name: Upload artifact
        run: ./gradlew :common-test:publish -Pversion="${{ env.RELEASE_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
