name: Release ktor-client-auth

on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    paths:
      - ktor-client-auth

jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'

      # Build
      - name: Test and build
        run: ./gradlew :ktor-client-auth:test :ktor-client-auth:build

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(echo $GITHUB_SHA | cut -c 1-12)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ktor-client-auth.${{ env.RELEASE_TAG }}
          release_name: ktor-client-auth.${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
      - name: Upload artifact
        run: ./gradlew :ktor-client-auth:publish -Pversion="${{ env.RELEASE_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
