name: Verify libs

on:
  push:
    branches-ignore:
      - main

jobs:
  verify-branches:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'

      # Build
      - name: Run Gradle Check
        run: ./gradlew check
